CREATE DATABASE `candice_test_shard_0`;
CREATE DATABASE `candice_test_shard_1`;
CREATE DATABASE `candice_test_shard_2`;
CREATE DATABASE `candice_test_shard_3`;
CREATE DATABASE `candice_test_shard_4`;
CREATE DATABASE `candice_test_shard_5`;
CREATE DATABASE `candice_test_shard_6`;
CREATE DATABASE `candice_test_shard_7`;
CREATE DATABASE `candice_test_shard_8`;
CREATE DATABASE `candice_test_shard_9`;

USE `candice_test_shard_0`;
CREATE TABLE `TEST_SHARD_00` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_01` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_02` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_03` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_04` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_05` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_06` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_07` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_08` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_09` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_1`;
CREATE TABLE `TEST_SHARD_10` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_11` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_12` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_13` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_14` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_15` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_16` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_17` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_18` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_19` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_2`;
CREATE TABLE `TEST_SHARD_20` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_21` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_22` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_23` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_24` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_25` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_26` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_27` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_28` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_29` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_3`;
CREATE TABLE `TEST_SHARD_30` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_31` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_32` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_33` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_34` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_35` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_36` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_37` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_38` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_39` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_4`;
CREATE TABLE `TEST_SHARD_40` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_41` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_42` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_43` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_44` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_45` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_46` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_47` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_48` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_49` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_5`;
CREATE TABLE `TEST_SHARD_50` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_51` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_52` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_53` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_54` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_55` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_56` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_57` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_58` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_59` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_6`;
CREATE TABLE `TEST_SHARD_60` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_61` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_62` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_63` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_64` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_65` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_66` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_67` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_68` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_69` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_7`;
CREATE TABLE `TEST_SHARD_70` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_71` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_72` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_73` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_74` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_75` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_76` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_77` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_78` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_79` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_8`;
CREATE TABLE `TEST_SHARD_80` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_81` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_82` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_83` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_84` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_85` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_86` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_87` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_88` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_89` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


USE `candice_test_shard_9`;
CREATE TABLE `TEST_SHARD_90` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_91` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_92` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_93` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_94` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_95` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_96` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_97` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_98` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


CREATE TABLE `TEST_SHARD_99` (
    `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `flux_no` VARCHAR(128) NOT NULL COMMENT 'shard col'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8 ;


